### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [skratchdot/elasticsearch-tools#7]
es-export-mappings --url http://localhost:9200 --file ~/backups/elasticsearch/prod/prod.mappings.json

###### *gives me the following*

/usr/local/lib/node_modules/elasticsearch-tools/node_modules/elasticsearch/src/lib/log.js:65
Log.prototype.listenerCount = function (event) {
                                       ^

RangeError: Maximum call stack size exceeded
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-tools/node_modules/elasticsearch/src/lib/log.js:65:40)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-tools/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-tools/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-tools/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-tools/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)

**Comment by KTachyon** [comment]
+1

**Comment by skratchdot** [comment]
It's been a while since I've looked at this.  Are you guys on the latest version of Elasticsearch?  I guess it's about time to update the driver in this repo, and add some tests.  Is the mapping you are trying to export massive? I'm guessing I need to change the logging level when initializing the ES driver, but I'll need to look into it.  Seems this repo is still on 2.4 of the driver, so the issue is somewhere: https://github.com/elastic/elasticsearch-js/blob/aa2a3fbd61db6601bd91e0dbd26235e68615350e/src/lib/log.js

**Comment by wheredoesyourmindgo** [comment]
yeah. I'm using the latest.

**Comment by maqboolkhan** [comment]
+1
kindly fix it i love your software but now its totally becomes useless :cry:

**Comment by skratchdot** [comment]
I want to take a look, but haven't had time lately.  I stopped using ES in production, so haven't had time to revisit this lib after recent elasticsearch upgrades.  Hoping someone else can take a look, or I'll try to get around to it when I have a bit of time...

**Comment by maqboolkhan** [comment]
@skratchdot oky my best wishes are with u :+1:

**Comment by orweinberger** [comment]
I found that updating the `elasticsearch` package in the `package.json` file resolved these errors.

**Comment by skratchdot** [comment]
@orweinberger - :This is great! I'm going to update, and re-publish.  Thanks for this!

**Comment by AseedUsmani** [comment]
I am still getting it even when I am using elasticsearch 5.0.0
